export default {

  SET_ALIAS: "SET_ALIAS",
  SET_URL: "SET_URL",
  SET_DESCRIPTION: "SET_DESCRIPTION",
  GO_LINKS_FETCH: "GO_LINKS_FETCH",
  GO_LINKS_FETCH_LOADING: "GO_LINKS_FETCH_LOADING",
  GO_LINKS_FETCH_SUCCESS: "GO_LINKS_FETCH_SUCCESS",
  GO_LINKS_FETCH_FAILURE: "GO_LINKS_FETCH_FAILURE",
};
