export default {
  SET_ALIAS: "SET_ALIAS",
  SET_URL: "SET_URL",
  SET_DESCRIPTION: "SET_DESCRIPTION",
  GO_LINKS_FETCH: "GO_LINKS_FETCH",
  POPULATE_EDIT_INFO: "POPULATE_EDIT_INFO",
  POPULATE_ALIAS_INFO: "POPULATE_ALIAS_INFO",
  CLEAR_EDIT_INFO: "CLEAR_EDIT_INFO",
  GO_LINK_UPDATING: "GO_LINK_UPDATING",
};
