export default {
  SORT_BY_ID_ASCENDING: 'SORT_BY_ID_ASCENDING',
  SORT_BY_ID_DESCENDING: 'SORT_BY_ID_DESCENDING',
  SORT_BY_NAME_ASCENDING: 'SORT_BY_NAME_ASCENDING',
  SORT_BY_NAME_DESCENDING: 'SORT_BY_NAME_DESCENDING',
};
