export default {
  GO_LINKS_SUCCESS: "GO_LINKS_SUCCESS",
  GO_LINKS_FAILURE: "GO_LINKS_FAILURE",
  GO_LINKS_LOADING: "GO_LINKS_LOADING",

  SAVE_SUCCESS: "SAVE_SUCCESS",
  SAVE_FAILURE: "SAVE_FAILURE",

  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",

  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILURE: "DELETE_FAILURE",
};
