export default {
  GO_LINKS: {
    LOADING: "GO_LINKS_LOADING",
    SUCCESS: "GO_LINKS_SUCCESS",
    FAILURE: "GO_LINKS_FAILURE",
  },

  SAVE: {
    SUCCESS: "SAVE_SUCCESS",
    FAILURE: "SAVE_FAILURE",
  },

  DELETE: {
    SUCCESS: "DELETE_SUCCESS",
    FAILURE: "DELETE_FAILURE",
  },

  UPDATE: {
    SUCCESS: "UPDATE_SUCCESS",
    FAILURE: "UPDATE_FAILURE",
  },
};
