source 'http://gemserver.liveramp.net/'

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner', '1.4.1'
  gem 'headless', '1.0.2'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'letter_opener'
  gem 'awesome_print'
  gem 'rspec-rails', '~> 3.0'
  gem 'passenger', '~> 5.0'
end
group :test do
  gem 'rack_session_access', '~> 0.1.1'
  gem 'selenium-webdriver'
  gem 'shoulda'
  gem 'factory_girl_rails', '~> 4.0'
end

gem 'rails_logger', :git => 'git@git.liveramp.net:RailsRepos/rails_logger.git'
gem 'active_attr', '0.8.5'
gem 'haml', '~> 4.0'
gem 'gon', '~> 6.0'
gem 'uglifier', '2.7.2'
gem 'mysql2', '~> 0.4.2'
gem 'rails', '4.2.5'
gem 'redis-rails', '4.0.0'
gem 'thrift', '0.9.3.0'
gem 'liveramp_auth', git: 'git@git.liveramp.net:RailsRepos/liveramp_auth.git'
gem 'auth_service_client', git: 'git@git.liveramp.net:RailsRepos/auth_service.git'
gem 'exception_notification', '~> 4.1.4'

# gem 'rails_assets', git: 'git@git.liveramp.net:RailsRepos/rails_assets.git'
# gem 'rails_assets', path: '../rails_assets'

gem 'subdomain_routes', git: 'git@git.liveramp.net:RailsRepos/subdomain_routes.git'

gem 'newrelic_rpm', '~> 3.14'
gem 'js-routes', '~> 1.1'
gem 'select2-rails', '3.5.9'
gem 'font-awesome-rails', '4.6.3.1'
gem 'jquery-rails', '~> 4.1'
gem 'jquery-ui-rails', '~> 5.0'
gem 'protected_attributes', '~> 1.1'
gem 'sprockets-rails', '~> 2.0'
gem 'bootstrap-sass', '~> 3.3'
gem 'sass-rails', '~> 5.0'
gem 'autoprefixer-rails', '~> 6'
gem 'httparty', '0.13.7'
