kind: Service
apiVersion: v1
metadata:
  name: go-links
  namespace: tupperware-test
  labels:
    app: go-links
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: go-links
