admin:
  url: localhost:3000

audience:
  url: localhost:3001

destination:
  url: localhost:3002

company:
  url: localhost:3003

endpoint:
  url: localhost:3004

customerlink:
  url: localhost:3005

taxonomy_endpoint:
  url: localhost:3006

