go_links_db_base: &GO_LINKS_DB_BASE
  adapter: mysql2
  encoding: utf8
  reconnect: true
  url: <%= ENV['GO_LINKS_DATABASE_URL'] %>
production:
  <<: *GO_LINKS_DB_BASE
  retries: 0
  pool: 5
  reaping_frequency: 60
  wait_timeout: 28800
staging:
  <<: *GO_LINKS_DB_BASE
development:
  <<: *GO_LINKS_DB_BASE
test:
  <<: *GO_LINKS_DB_BASE
