production:
  adapter: mysql2
  username: rapleaf_dev
  password: z6NmnjqruhnTxw
  database: rapleaf_production
  host: rldb-dev.liveramp.net
  encoding: utf8
  reconnect: true

development:
  adapter: mysql2
  username: rapleaf_dev
  password: z6NmnjqruhnTxw
  database: rapleaf_production
  host: rldb-dev.liveramp.net
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: rapleaf_test
  encoding: utf8
  reconnect: true

local_db:
  adapter: mysql2
  username: root
  password:
  database: local_db
  host: localhost
  encoding: utf8
  reconnect: true
