go_links_db_base: &GO_LINKS_DB_BASE
  adapter: mysql2
  url: <%= ENV.fetch('GO_LINKS_DATABASE_URL') %>
  encoding: utf8
  reconnect: true

production:
  <<: *GO_LINKS_DB_BASE

test:
  <<: *GO_LINKS_DB_BASE
