development:
  adapter: mysql2
  username: root
  password:
  database: go_links_local
  host: localhost
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: go_links_test
  encoding: utf8
  reconnect: true
