production:
  database: go_links_db
  username: go_links_user
  password: "<%= Rails.application.secrets.go_links_password %>"
  host: "<%= Rails.application.secrets.go_links_host %>"
  encoding: utf8
  reconnect: 'true'
  adapter: mysql2
  retries: 0
  pool: 5
  reaping_frequency: 60
  wait_timeout: 28800
development:
  database: go_links_db_development
  username: go_links_user
  password: "<%= Rails.application.secrets.go_links_password %>"
  host: "<%= Rails.application.secrets.go_links_host %>"
  encoding: utf8
  reconnect: 'true'
  adapter: mysql2
  retries: 0
  pool: 5
  reaping_frequency: 60
  wait_timeout: 28800
local:
  adapter: mysql2
  username: root
  password:
  database: go_links_db_local
  host: localhost
  encoding: utf8
  reconnect: true
test:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: go_links_db_test
  encoding: utf8
  reconnect: true
