development:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: rapleaf_test
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: rapleaf_test
  encoding: utf8
  reconnect: true

