production: # we use production rails env in development deploys
  secret_key_base: 9vrWgICyWsKKlFQNwXNe69TFMbCvTLIYGChVMyCl
  go_links_host: go-links-db.liveramp.net
  rldb_password:
development:
  secret_key_base: uQ7mOU0Al87OZMwAp3gVhmPxf5h3CrRP2kgznkTw
  go_links_host: go-links-db-dev.liveramp.net
  rldb_password:
