#!/bin/bash

hvault_path=secret/fodor/go_links/secrets.yml

echo 'Grabbing configs for go_links [development] from hvault...'
if ! vault read -field=development $hvault_path > config/secrets.yml; then
  echo '***  Failed to fetch secrets from Hashicorp Vault!  ***'
  echo 'You might need to auth, or re-auth, with the following command:'
  echo '    vault auth -method=ldap'
fi
